name: Test Release to test.pypi.org

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true


jobs:
    release-test-wheel:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - name: Setup Fresh Virtual Environment
            run: |
              pip install --upgrade pip
              python3.10 -m venv env
              export PATH=$PATH:/home/docker/.local/bin
              source env/bin/activate
              echo "VIRTUAL ENV:" $VIRTUAL_ENV  
          - name: Install Packaging Dependencies
            run: pip install build twine
          - name: Package
            env:
              VERSION: ${{ github.event.inputs.version }}
            run: bash scripts/wheel.sh $(echo $VERSION | sed 's/^refs\/tags\/v//')
          - name: Publish
            env:
              TWINE_USERNAME: __token__
              TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
              VERSION: ${{ github.event.inputs.version }}
            run: bash scripts/pypi-release.sh lmql-$(echo $VERSION | sed 's/^refs\/tags\/v//')